name: DEBUG WORKSPACE

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Print working directory
        run: |
          echo "PWD:"
          pwd

      - name: Print GITHUB_WORKSPACE
        run: |
          echo "GITHUB_WORKSPACE:"
          echo $GITHUB_WORKSPACE

      - name: List workspace root
        run: |
          echo "==== ls $GITHUB_WORKSPACE ===="
          ls -la $GITHUB_WORKSPACE

      - name: Recursive search for requirements.txt
        run: |
          echo "==== find requirements.txt ===="
          find /home/runner/work -name requirements.txt
